:toc:

# Tambua
"Tambua", which is Swahili for "classify" or "identify"?

# Tensorflow Lite Build

The library can be build and installed in two different ways:
* As conan package
* As CMake project with dependencies

## Build/Install with Conan
Get the conan package management
----
brew install conan
----
The requirement:
----
self.requires("tensorflow-lite/2.12.0")
----
Detect the profile
----
conan profile detect
----
Build the project
----
conan build . --build=missing
----
Build the project debug
----
conan build . -s build_type=Debug --build=missing
----

## Build/Install just with CMake

Install dependencies:
----
sudo apt install libabsl-dev libeigen3-dev
----
The library can be downloaded and build from following link:
----
git clone https://github.com/tensorflow/tensorflow.git tflite_src
----
Following patch needs to be applied:
----
cd tensorflow_src
git apply ../Tambua/install.patch
----
Prepare folder structure:
----
rm -fr build
rm -fr tflite_build
rm -fr tflite_install
mkdir tflite_build
cd tflite_build
----
There is known issue in the building process which needs to be corrected in file: tensorflow/lite/tools/cmake/modules/ml_dtypes/CMakeLists.txt
----
-target_include_directories(ml_dtypes INTERFACE
- "${ML_DTYPES_SOURCE_DIR}"
- "${ML_DTYPES_SOURCE_DIR}/ml_dtypes")
+target_include_directories(ml_dtypes INTERFACE
+  "$<BUILD_INTERFACE:${ML_DTYPES_SOURCE_DIR}>" "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
+  "$<BUILD_INTERFACE:${ML_DTYPES_SOURCE_DIR}/ml_dtypes>" "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/ml_dtypes>")
----
Configure tensorflow lite project (will be installed to the /Users/jan/TFLite):
----
cmake ../tflite_src/tensorflow/lite \
    -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/tflite_install \
    -DTFLITE_KERNEL_TEST=OFF \
    -DTFLITE_ENABLE_INSTALL=ON \
    -DTFLITE_ENABLE_XNNPACK=OFF \
    -DTFLITE_ENABLE_GPU=OFF \
    -DTFLITE_ENABLE_RUY=OFF \
    -DTFLITE_ENABLE_NNAPI=OFF \
    -DTFLITE_ENABLE_NNAPI_VERBOSE_VALIDATION=OFF \
    -DTFLITE_ENABLE_MMAP=OFF \
    -DTFLITE_ENABLE_LABEL_IMAGE=ON \
    -DTFLITE_ENABLE_RESOURCE=OFF \
    -DTFLITE_ENABLE_METAL=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DFETCHCONTENT_FULLY_DISCONNECTED=OFF \
    -Wno-dev
----
Output with some errors but it is ok
----
-- Configuring done (193.5s)
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "ruy" that is not in any export set.
-- Generating done (0.2s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
----
Build the project
----
make -j $(nproc) //Linux
make -j $(sysctl -n hw.physicalcpu)
----
Install the project
----
cmake --install .
----

# Resources

* Workinstruction to build TFL link:https://github.com/bastien-sagetat/photohead/blob/main/doc/soft_requirements.md[Repository from Bastien Segatat]
* TFL Issue tractking: link:https://github.com/tensorflow/tensorflow/issues/62381[GitHub TensorFlow]

