:toc:

## Configuration issues

here are some common issues that you may encounter when installing Qt: self.requires("qt/6.7.1")

### Qt apt packages issues

The conan dependency manager may not be able to find the required APT packages on the Ubuntu.
It tries to install them by apt but it has not permissions to it

Solution: Run the conan install command with sudo in fist run to install the required packages
** remember the conan configuration will be in root folder in this case so transfere your conan configuration to the root folder
----
sudo conan install conanfile.py --output-folder=./build/$preset --build=missing --profile=$preset --profile:build=linux-release -c tools.system.package_manager:mode=install
----

### Qt installation issues

1. The imported target "clangBasic" references the file "/usr/lib/llvm-18/lib/libclangBasic.a"

solution description: link:https://askubuntu.com/questions/1220739/llvm-dev-package-missing-libclangbasic[AskUbuntu]

Solution 1: Install the required version of LLVM
----
sudo apt install llvm
sudo apt install libclang-dev
----

2. The build fails as it build will all available cores

Solution 1: Limit the number of cores used by the build process
Meanwhile, and for special cases, tools.cpu_count() is the way to manage it, because it will detect cores and also is user-configurable in conan.conf and with environment variables.
----
env var CONAN_CPU_COUNT
cpu_count var in conan.conf
Do not specify= will use all the cores
----

Solution 2: Run the build manually
----
cmake --build "/home/jan/.conan2/p/b/qtf3b548ccb1889/b/build/Debug" -- -j4
----

NOTE: Disable hibernation during the build process:

----
sudo systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
-- unmask --
----
